name: Deploy no K8S
on:
    workflow_call: 
permissions:
   id-token: write
   contents: read
   actions: read

jobs:
    deploy-homolog:
        name: Deploy Homolog
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set Context K8S
              uses: azure/k8s-set-context@v5
              with:
                method: kubeconfig
                kubeconfig: ${{secrets.K8S_CONFIG}}

            - name: Deloy no K8S
              uses: Azure/k8s-deploy@v5
              with:
                manifests: |
                   k8s/deployment.yaml
                images: |
                     ${{vars.DOCKERHUB_USER}}/projeto-devops-pro:v${{github.run_number}}
            
        

