name: Deploy no K8S
on:
    workflow_call: 
        inputs:
            environment-name:
                type: string
                required: true
            environment-url:
                type: string
                required: true

jobs:
    deploy-homolog:
        name: Deploy Homolog
        runs-on: ubuntu-latest
        environment:
            name: ${{inputs.environment-name}}
            url: ${{inputs.environment-url}}
        steps:
            - uses: actions/checkout@v4

            - name: Login to AWS with access keys
              uses: KoalaOps/login-aws@v1
              with:
                aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws_region: us-east-1
                enable_ecr_login: true               

            - name: Set Context K8S
              uses: azure/k8s-set-context@v5
              with:
                method: kubeconfig
                kubeconfig: ${{secrets.K8S_CONFIG}}

            - name: Update Deployment
              run: "sed -i 's/host: homologacao.danferreira.vip/host: ${{vars.BASE_URL}}/g' k8s/deployment.yaml"

            - name: Deploy no K8S
              uses: Azure/k8s-deploy@v5
              with:
                namespace: ${{secrets.K8S_NAMESPACES}}
                manifests: |
                   k8s/deployment.yaml
                images: |
                     ${{vars.DOCKERHUB_USER}}/projeto-devops-pro:v${{github.run_number}}
            
        

